### PR TITLE
Version for Compose 1.7.0

### PR DESCRIPTION
**Pull request by andrey-ananiev**
This version of library can work with Compose 1.7.0

### CODE REVIEW

**Comment by philipkraeutl** [comment]
would be nice if this PR could be merged 🙏

**Comment by WojciechOsak** [comment]
Thanks @andrey-ananiev and @philipkraeutl ! Release will be done today

**Comment by WojciechOsak** [comment]
There are some issues with release, I need to dig into, sorry but it will be delivered in next two weeks.

**Comment by WojciechOsak** [comment]
@andrey-ananiev @philipkraeutl 1.0.2 is out, please try it!

**Pull request merged**
